### ISSUE TITLE
Rewrite it in WASM 😸

### ISSUE THREAD

**Issue by rakhid16** [mramirid/my-doctor#1]
https://webassembly.org/docs/use-cases/

**Comment by mramirid** [comment]
yeah, we should 🚀 rewrite it 🚀 in wasm 🚀 to make it 🚀 blazingly fast 🚀, memory efficient 🚀, minimal runtime 🚀, and blah blah blah. Make the app faster and fasterer! 🚀🚀🚀🚀🚀🚀
