### ISSUE TITLE
Rewrite in java sir

### ISSUE THREAD

**Issue by let-me-cook** [mramirid/my-doctor#2]
pls sir rewrite in java i need this  for my college assignment ser

![image](https://user-images.githubusercontent.com/35270908/147037345-12e0af72-649c-426a-9633-9479c37b4e48.png)

pls do the needful sir

![image](https://user-images.githubusercontent.com/35270908/147037222-f751b205-99bd-4b04-87a1-d82e7955005e.png)

**Comment by mramirid** [comment]
Universities should move their students away from java because it's really unbased from now on

**Comment by mramirid** [comment]
Closed as of #1 

WASM to the moon 🚀🌑

**Comment by let-me-cook** [comment]
cringe
